/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'pratyusha' at '2/18/17 10:50 AM' with Gradle 2.14.1
 *
 * @author pratyusha, @date 2/18/17 10:50 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
